name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    
    - name: Build and test
      run: xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIDNING_REQUIRED=NO
